version: "3.0"
services:
  recipes:
        build: .
        image: recipes-api 
        container_name: recipes_api
        restart: always 
        ports:
          - 4301:3001
        networks:
          - app-network
  nginx:
    image: nginx:alpine
    container_name: recipe-web-proxy
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9029:9090
    depends_on:
      - recipes 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
