import { buildSchema } from "type-graphql";
import {
  UserResolver,
  SecurityResolver,
  CreateRecipeResolver,
  ActivityCategoryResolver,
  RecipesListResolver,
  RecipeCategoryResolver,
  SpecialConditionResolver,
  DeleteRecipeResolver,
  RecipeItemResolver,
  RecordCategoryResolver,
  CreateRecordResolver,
  RecordListResolver,
  MoodResolver,
  UserInfoResolver,
  NutritionGuideResolver,
  RecipeNutritionResolver,
  CreateActivityResolver,
  MoodOverviewResolver,
  CookedRecipeResolver,
  NutritionOverviewResolver,
  SeedNutritionRecomendationResolver,
  RequestEarlyAccessResolver,
  ActivityCaloriesResolver,
  ActivityOverviewResolver,
  UserPasswordResolver,
  CreateMealsResolver,
  ListMealsResolver,
  SearchRecipeResolver,
  ActivityListResolver,
  MealRecipeResolver,
  MealNutritionResolver,
  // ***** admin resolvers ******
  AdminAuthResolver,
  AdminRecipeCategoryResolver,
  AdminUserResolver,
  AdminRecipeResolver,
} from "../resolvers";

export const build = async () => {
  return await buildSchema({
    resolvers: [
      UserResolver,
      SecurityResolver,
      CreateRecipeResolver,
      ActivityCategoryResolver,
      RecipesListResolver,
      RecipeCategoryResolver,
      SpecialConditionResolver,
      DeleteRecipeResolver,
      RecipeItemResolver,
      RecordCategoryResolver,
      CreateRecordResolver,
      RecordListResolver,
      MoodResolver,
      UserInfoResolver,
      NutritionGuideResolver,
      RecipeNutritionResolver,
      CreateActivityResolver,
      MoodOverviewResolver,
      CookedRecipeResolver,
      NutritionOverviewResolver,
      SeedNutritionRecomendationResolver,
      RequestEarlyAccessResolver,
      ActivityCaloriesResolver,
      ActivityOverviewResolver,
      UserPasswordResolver,
      CreateMealsResolver,
      ListMealsResolver,
      SearchRecipeResolver,
      ActivityListResolver,
      MealRecipeResolver,
      AdminAuthResolver,
      AdminRecipeCategoryResolver,
      AdminUserResolver,
      AdminRecipeResolver,
      MealNutritionResolver,
    ],
    validate: false,
    dateScalarMode: "isoDate",
  });
};
