import { buildSchema } from "type-graphql";
import {
  UserResolver,
  SecurityResolver,
  CreateRecipeResolver,
  ActivityCategoryResolver,
  RecipesListResolver,
  RecipeCategoryResolver,
  SpecialConditionResolver,
  DeleteRecipeResolver,
  RecipeItemResolver,
  RecordCategoryResolver,
  CreateRecordResolver,
  RecordListResolver,
  MoodResolver,
  UserInfoResolver,
  NutritionGuideResolver,
  RecipeNutritionResolver,
  CreateActivityResolver,
  MoodOverviewResolver,
  CookedRecipeResolver,
  NutritionOverviewResolver,
  SeedNutritionRecomendationResolver,
  RequestEarlyAccessResolver,
  ActivityCaloriesResolver,
  ActivityOverviewResolver,
  UserPasswordResolver,
  CreateMealsResolver,
  ListMealsResolver,
  SearchRecipeResolver,
  ActivityListResolver,
  MealRecipeResolver,
  MealNutritionResolver,
  HealthLabelsResolver,
  // *****  admin resolvers  *****
  AdminAuthResolver,
  AdminRecipeCategoryResolver,
  AdminUserResolver,
  AdminRecipeResolver,
  // *****  diet resolvers  ******
  DietDataResolver,
  DietConfigResolver,
  FoodFilterResolver,
  MacrosResolver,
  DietRecordResolver,
  // ****** translation ******
  TranlatingResolver,
  // nutrients
  NutrientCategoryResolver,
  NutritionIntakeResolver,
  NutrionIntakeChartResolver,
  // ******* RECIPES ********
  RecomendedRecipesResolver,
  // ******* Nutritients plans ******
  PlansListResolver,
} from "../resolvers";
export const build = async () => {
  return await buildSchema({
    resolvers: [
      UserResolver,
      SecurityResolver,
      CreateRecipeResolver,
      ActivityCategoryResolver,
      RecipesListResolver,
      RecipeCategoryResolver,
      SpecialConditionResolver,
      DeleteRecipeResolver,
      RecipeItemResolver,
      RecordCategoryResolver,
      CreateRecordResolver,
      RecordListResolver,
      MoodResolver,
      UserInfoResolver,
      NutritionGuideResolver,
      RecipeNutritionResolver,
      CreateActivityResolver,
      MoodOverviewResolver,
      CookedRecipeResolver,
      NutritionOverviewResolver,
      SeedNutritionRecomendationResolver,
      RequestEarlyAccessResolver,
      ActivityCaloriesResolver,
      ActivityOverviewResolver,
      UserPasswordResolver,
      CreateMealsResolver,
      ListMealsResolver,
      SearchRecipeResolver,
      ActivityListResolver,
      MealRecipeResolver,
      AdminAuthResolver,
      AdminRecipeCategoryResolver,
      AdminUserResolver,
      AdminRecipeResolver,
      MealNutritionResolver,
      HealthLabelsResolver,
      DietDataResolver,
      DietConfigResolver,
      FoodFilterResolver,
      MacrosResolver,
      DietRecordResolver,
      TranlatingResolver,
      NutrientCategoryResolver,
      NutritionIntakeResolver,
      RecomendedRecipesResolver,
      NutrionIntakeChartResolver,
      PlansListResolver,
    ],
    validate: false,
    dateScalarMode: "isoDate",
  });
};
