version: "3.0"
services:
  security:
    build: .
    image: opencc
    container_name: opencc
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      - DB_NAME=opencc
      - DB_USER=eynak
      - DB_PASS=tsew
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network
  recipes:
    build: ./recipes
    image: recipes-ms
    container_name: recipes-ms
    restart: unless-stopped
    ports:
      - 4001:3001
    networks:
      - app-network
  db:
    build: ./docker/database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306
    networks:
      - app-network
    volumes:
      - ./docker/database/data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9090:9090
    depends_on:
      - security
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
