version: "3.0"
services:
  security:
    build: .
    image: vanillefraise 
    container_name: vanillefraise
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4019:4000
    environment:
      - DB_NAME=opencc
      - DB_USER=eynak
      - DB_PASS=tsew
      - DB_HOST=db
      - RECIPE_API_URL=http://recipes:3001/
    depends_on:
      - db 
    networks:
      - app-network
  db:
    container_name: vanillefraise_db
    build: ./docker/database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3310:3306
    networks:
      - app-network
    volumes:
      - ./docker/database/data:/var/lib/mysql
  recipes:
        build: ./recipes
        image: recipes-ms
        container_name: recipes_ms
        restart: always 
        ports:
          - 4300:3001
        networks:
          - app-network
  nginx:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9019:9090
    depends_on:
      - security
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
